/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class cartelera extends javax.swing.JFrame {

    /**
     * Creates new form cartelera
     */
    public cartelera() {
        initComponents();
               setIconImage(new ImageIcon(getClass().getResource("/imagenes/imgCam.png")).getImage());

        jL_Sala.setText("");
                    this.jL_Hora.setText("");

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTG_SALAS = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CB_Peliculas = new javax.swing.JComboBox();
        jL_ImagenPelicula = new javax.swing.JLabel();
        jPanel_Ficha = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jL_Titulo = new javax.swing.JLabel();
        jL_Duracion = new javax.swing.JLabel();
        jL_Clasificacion = new javax.swing.JLabel();
        jL_Genero = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jL_Sala = new javax.swing.JLabel();
        jL_Hora = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        RB_3D = new javax.swing.JRadioButton();
        RB_2D = new javax.swing.JRadioButton();
        RB_4D = new javax.swing.JRadioButton();
        RB_4DX = new javax.swing.JRadioButton();
        CB_Hora = new javax.swing.JComboBox<>();
        BT_Buy = new javax.swing.JButton();
        BT_Back = new javax.swing.JButton();
        BT_Cerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        if (RB_2D.isSelected()==true){
            this.jL_Sala.setText("2D");

        }
        if (RB_3D.isSelected()==true){
            this.jL_Sala.setText("3D");

        }
        if (RB_4D.isSelected()==true){
            this.jL_Sala.setText("4D");

        }
        if (RB_4DX.isSelected()==true){
            this.jL_Sala.setText("4DX");
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CARTELERA");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        CB_Peliculas.setBackground(new java.awt.Color(153, 153, 153));
        CB_Peliculas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione la película", "Chips", "Logan", "Fragmentado", "Kong: La isla calavera", "Blackhearis" }));
        CB_Peliculas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_PeliculasItemStateChanged(evt);
            }
        });

        jPanel_Ficha.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_Ficha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ficha", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel_Ficha.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TITULO: ");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DURACIÓN:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GÉNERO:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CLASIFICACIÓN:");

        jL_Titulo.setForeground(new java.awt.Color(255, 255, 255));

        jL_Duracion.setForeground(new java.awt.Color(255, 255, 255));

        jL_Clasificacion.setForeground(new java.awt.Color(255, 255, 255));

        jL_Genero.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SALA:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("HORA:");

        jL_Sala.setForeground(new java.awt.Color(255, 255, 255));

        jL_Hora.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_FichaLayout = new javax.swing.GroupLayout(jPanel_Ficha);
        jPanel_Ficha.setLayout(jPanel_FichaLayout);
        jPanel_FichaLayout.setHorizontalGroup(
            jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FichaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(44, 44, 44)
                .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jL_Duracion, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jL_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL_Genero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL_Clasificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Sala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_FichaLayout.createSequentialGroup()
                        .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Hora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel_FichaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 19, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel_FichaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel_FichaLayout.setVerticalGroup(
            jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FichaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jL_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jL_Duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Sala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_FichaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_FichaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel6))
                            .addGroup(jPanel_FichaLayout.createSequentialGroup()
                                .addComponent(jL_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jL_Clasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel_FichaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " SALAS DISPONIBLES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 53));

        RB_3D.setBackground(new java.awt.Color(51, 51, 51));
        RB_3D.setForeground(new java.awt.Color(255, 255, 255));
        BTG_SALAS.add(RB_3D);
        RB_3D.setText("3D");
        RB_3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_3DActionPerformed(evt);
            }
        });

        RB_2D.setBackground(new java.awt.Color(51, 51, 51));
        RB_2D.setForeground(new java.awt.Color(255, 255, 255));
        BTG_SALAS.add(RB_2D);
        RB_2D.setText("2D");
        RB_2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_2DActionPerformed(evt);
            }
        });

        RB_4D.setBackground(new java.awt.Color(51, 51, 51));
        RB_4D.setForeground(new java.awt.Color(255, 255, 255));
        BTG_SALAS.add(RB_4D);
        RB_4D.setText("4D");
        RB_4D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_4DActionPerformed(evt);
            }
        });

        RB_4DX.setBackground(new java.awt.Color(51, 51, 51));
        RB_4DX.setForeground(new java.awt.Color(255, 255, 255));
        BTG_SALAS.add(RB_4DX);
        RB_4DX.setText("4DX");
        RB_4DX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_4DXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RB_2D, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                .addComponent(RB_3D, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RB_4D)
                .addGap(9, 9, 9)
                .addComponent(RB_4DX)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB_3D)
                    .addComponent(RB_4D)
                    .addComponent(RB_2D)
                    .addComponent(RB_4DX))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CB_Hora.setBackground(new java.awt.Color(153, 153, 153));
        CB_Hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione horario" }));
        CB_Hora.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_HoraItemStateChanged(evt);
            }
        });

        BT_Buy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonBuy1.png"))); // NOI18N
        BT_Buy.setBorder(null);
        BT_Buy.setBorderPainted(false);
        BT_Buy.setContentAreaFilled(false);
        BT_Buy.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        BT_Buy.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonBuy2.png"))); // NOI18N
        BT_Buy.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BT_Buy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BT_Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_BuyActionPerformed(evt);
            }
        });

        BT_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonBack1.png"))); // NOI18N
        BT_Back.setBorder(null);
        BT_Back.setBorderPainted(false);
        BT_Back.setContentAreaFilled(false);
        BT_Back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BT_Back.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonBack2.png"))); // NOI18N
        BT_Back.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BT_Back.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BT_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jL_ImagenPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CB_Peliculas, 0, 160, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CB_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel_Ficha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(BT_Buy)
                        .addGap(47, 47, 47)
                        .addComponent(BT_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CB_Peliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jL_ImagenPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CB_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jPanel_Ficha, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BT_Buy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT_Back))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 140, 720, 340);

        BT_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        BT_Cerrar.setBorder(null);
        BT_Cerrar.setBorderPainted(false);
        BT_Cerrar.setContentAreaFilled(false);
        BT_Cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BT_Cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar2.png"))); // NOI18N
        BT_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(BT_Cerrar);
        BT_Cerrar.setBounds(740, 0, 53, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 610);

        setSize(new java.awt.Dimension(796, 611));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CB_PeliculasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_PeliculasItemStateChanged
        // TODO add your handling code here:
                this.CB_Hora.removeAllItems();
        int imagenPeli = this.CB_Peliculas.getSelectedIndex();
        // chips, logan, fragmentado, kong, blackhearis
        // consultar información en cine.colombia.com/cartelera.aspx
                

        switch (imagenPeli) {
            case 0:
                

                jPanel_Ficha.setVisible(true);

                break;

            case 1:
                jPanel_Ficha.setVisible(true);
                this.jL_Sala.setText("");

                RB_2D.setVisible(true);
                RB_3D.setVisible(true);
                RB_4D.setVisible(false);
                RB_4DX.setVisible(false);
                ImageIcon img1 = new ImageIcon(this.getClass().getResource("/imagenes/chips.jpg"));
                this.jL_ImagenPelicula.setIcon(img1);
                this.jL_Titulo.setText("CHIPS");
                this.jL_Duracion.setText("100 min");
                this.jL_Genero.setText("Comedia");
                this.jL_Clasificacion.setText("Mayores de 15 años");
                break;
            case 2:
                jPanel_Ficha.setVisible(true);
                this.jL_Sala.setText("");

                RB_4D.setVisible(true);
                RB_2D.setVisible(true);
                RB_4DX.setVisible(false);
                RB_3D.setVisible(true);
                ImageIcon img2 = new ImageIcon(this.getClass().getResource("/imagenes/logan.png"));
                this.jL_ImagenPelicula.setIcon(img2);
                this.jL_Titulo.setText("LOGAN");
                this.jL_Duracion.setText("120 min");
                this.jL_Genero.setText("Acción");
                this.jL_Clasificacion.setText("Mayores de 15 años");

                break;
            case 3:
                jPanel_Ficha.setVisible(true);
                this.jL_Sala.setText("");

                RB_4DX.setVisible(true);
                RB_3D.setVisible(true);
                RB_4D.setVisible(false);
                RB_2D.setVisible(false);
                ImageIcon img3 = new ImageIcon(this.getClass().getResource("/imagenes/fragmentado.jpg"));
                this.jL_ImagenPelicula.setIcon(img3);
                this.jL_Titulo.setText("FRAGMENTADO");
                this.jL_Duracion.setText("117 min");
                this.jL_Genero.setText("Thiller");
                this.jL_Clasificacion.setText("Mayores de 16 años");
                break;
            case 4:
                jPanel_Ficha.setVisible(true);
                this.jL_Sala.setText("");

                RB_2D.setVisible(true);
                RB_4D.setVisible(true);
                RB_3D.setVisible(false);
                RB_4DX.setVisible(false);
                ImageIcon img4 = new ImageIcon(this.getClass().getResource("/imagenes/kong.png"));
                this.jL_ImagenPelicula.setIcon(img4);
                this.jL_Titulo.setText("KONG: La isla calavera");
                this.jL_Duracion.setText("118 min");
                this.jL_Genero.setText("Aventura");
                this.jL_Clasificacion.setText("No recomendada para menores de 12 años");
                break;
            case 5:
                jPanel_Ficha.setVisible(true);
                this.jL_Sala.setText("");

                RB_4D.setVisible(true);
                RB_4DX.setVisible(true);
                RB_3D.setVisible(false);
                RB_2D.setVisible(false);
                ImageIcon img5 = new ImageIcon(this.getClass().getResource("/imagenes/blackhearis.jpg"));
                this.jL_ImagenPelicula.setIcon(img5);
                this.jL_Titulo.setText("BLACKHEARIS");
                this.jL_Duracion.setText("83 min");
                this.jL_Genero.setText("Documental");
                this.jL_Clasificacion.setText("Mayores de 15 años");
                break;
            default:
                jL_ImagenPelicula.setIcon(null);
                jPanel_Ficha.setVisible(false);

                break;

        }
    }//GEN-LAST:event_CB_PeliculasItemStateChanged

    private void BT_BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_BuyActionPerformed
        // TODO add your handling code here:
        int imagenPeli = this.CB_Peliculas.getSelectedIndex();

        String sala = this.jL_Sala.getText(), horario= this.jL_Hora.getText();

        if (imagenPeli != 0 && (sala.equalsIgnoreCase("") == false) && (horario.equalsIgnoreCase("")==false)) {

            
             if (JOptionPane.showConfirmDialog(rootPane, "¿Desea confirmar selección?",
                "Confirmar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.dispose();
           
        
             factura miFact = new factura();
             miFact.setVisible(true);
             
             factura.jL_TituloFact.setText((String)jL_Titulo.getText());
                          factura.jL_SalaFact.setText(jL_Sala.getText());
             factura.jL_HoraFact.setText(jL_Hora.getText());

             
             }

        } else {
            JOptionPane.showMessageDialog(null, "Todas las opciones son obligatorias", "Inválido", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_BT_BuyActionPerformed

    private void RB_3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_3DActionPerformed
        // TODO add your handling code here:
               

     
            this.jL_Sala.setText("3D");
                    this.jL_Hora.setText("");


        int hora = CB_Peliculas.getSelectedIndex();
         this.CB_Hora.removeAllItems();

        if (hora==1) { this.CB_Hora.addItem("Seleccione horario");
        this.CB_Hora.addItem("10:00 am");
        this.CB_Hora.addItem("2:00 pm");
        this.CB_Hora.addItem("4:00 pm");
        }
        if(hora==2){this.CB_Hora.addItem("Seleccione horario");
        this.CB_Hora.addItem("8:00 am");
        this.CB_Hora.addItem("6:00 pm");
        }
        if (hora==3){
        this.CB_Hora.addItem("Seleccione horario");
        this.CB_Hora.addItem("8:00 pm");
        this.CB_Hora.addItem("10:00 pm");
       }
    }//GEN-LAST:event_RB_3DActionPerformed

    private void RB_4DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_4DActionPerformed
        // TODO add your handling code here:
            

        
            this.jL_Sala.setText("4D");
                        this.jL_Hora.setText("");

            int hora = CB_Peliculas.getSelectedIndex();
 this.CB_Hora.removeAllItems();
        if (hora==2) { this.CB_Hora.addItem("Seleccione horario");
        this.CB_Hora.addItem("10:00 am");
        this.CB_Hora.addItem("12:00 m");
        
        }
        if(hora==4){this.CB_Hora.addItem("Seleccione horario");
        this.CB_Hora.addItem("8:00 pm");
        this.CB_Hora.addItem("4:00 pm");
        }
        if (hora==5){
        this.CB_Hora.addItem("Seleccione horario");
                this.CB_Hora.addItem("2:00 pm");

        this.CB_Hora.addItem("6:00 pm");
        this.CB_Hora.addItem("10:00 pm");
        }
        
    }//GEN-LAST:event_RB_4DActionPerformed

    private void RB_2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_2DActionPerformed
        // TODO add your handling code here:
                

        
            this.jL_Sala.setText("2D");
                    this.jL_Hora.setText("");

        
          int hora = CB_Peliculas.getSelectedIndex();
 this.CB_Hora.removeAllItems();
        if (hora==1) { this.CB_Hora.addItem("Seleccione horario");
        this.CB_Hora.addItem("10:00 am");
        this.CB_Hora.addItem("2:00 pm");
        
        }
        if(hora==2){this.CB_Hora.addItem("Seleccione horario");
        this.CB_Hora.addItem("12:00 m");
        this.CB_Hora.addItem("4:00 pm");
        }
        if (hora==4){
        this.CB_Hora.addItem("Seleccione horario");
                
        this.CB_Hora.addItem("7:00 pm");

        
       
        }
    }//GEN-LAST:event_RB_2DActionPerformed

    private void RB_4DXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_4DXActionPerformed
        // TODO add your handling code here:
        this.CB_Hora.removeAllItems();
        
            this.jL_Sala.setText("4DX");
            this.jL_Hora.setText("");
        
          int hora = CB_Peliculas.getSelectedIndex();

        if (hora==3) { this.CB_Hora.addItem("Seleccione horario");
        this.CB_Hora.addItem("12:00 m");
        this.CB_Hora.addItem("3:00 pm");
        
        }
        if(hora==5){this.CB_Hora.addItem("Seleccione horario");
        this.CB_Hora.addItem("5:30 pm");
        this.CB_Hora.addItem("8:00 pm");
        }
       
    }//GEN-LAST:event_RB_4DXActionPerformed

    private void CB_HoraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_HoraItemStateChanged
        // TODO add your handling code here:
        
        
        int horario=this.CB_Hora.getSelectedIndex();
        
        switch(horario){
            case 1: 
                this.jL_Hora.setText(CB_Hora.getSelectedItem().toString());
                break;
            case 2: this.jL_Hora.setText(CB_Hora.getSelectedItem().toString());
            break;
            case 3:
                this.jL_Hora.setText(CB_Hora.getSelectedItem().toString());
                break;
            case 4: 
                this.jL_Hora.setText(CB_Hora.getSelectedItem().toString());
                break;
            
        }

        
    }//GEN-LAST:event_CB_HoraItemStateChanged

    private void BT_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_BackActionPerformed
        // TODO add your handling code here
        if (JOptionPane.showConfirmDialog(rootPane, "\n¿Desea regresar?",
                "Confirmar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
        this.dispose();
         
        this.dispose();
         index miIndex = new index();
       miIndex.setVisible(true);
        }
    }//GEN-LAST:event_BT_BackActionPerformed

    private void BT_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CerrarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "\n¿Desea salir del programa?",
            "Confirmar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
        System.exit(0);}

    }//GEN-LAST:event_BT_CerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cartelera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BTG_SALAS;
    private javax.swing.JButton BT_Back;
    public javax.swing.JButton BT_Buy;
    private javax.swing.JButton BT_Cerrar;
    public javax.swing.JComboBox<String> CB_Hora;
    public javax.swing.JComboBox CB_Peliculas;
    private javax.swing.JRadioButton RB_2D;
    private javax.swing.JRadioButton RB_3D;
    private javax.swing.JRadioButton RB_4D;
    private javax.swing.JRadioButton RB_4DX;
    private javax.swing.JLabel jL_Clasificacion;
    private javax.swing.JLabel jL_Duracion;
    private javax.swing.JLabel jL_Genero;
    public javax.swing.JLabel jL_Hora;
    private javax.swing.JLabel jL_ImagenPelicula;
    public javax.swing.JLabel jL_Sala;
    public javax.swing.JLabel jL_Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Ficha;
    // End of variables declaration//GEN-END:variables
}
