/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;


import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterJob;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**implements Printable
 *
 * @author Alumno
 */
public class factura extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form cartelera
     */
    public factura() {
        initComponents();
               setIconImage(new ImageIcon(getClass().getResource("/imagenes/imgCam.png")).getImage());

        jL_SalaFact.setText("");
        this.jL_SillasFact.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Ficha = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jL_TituloFact = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jL_SalaFact = new javax.swing.JLabel();
        jL_SillasFact = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jL_HoraFact = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cantSillas = new javax.swing.JLabel();
        jPanel_Ficha1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jT_NombreFact = new javax.swing.JTextField();
        jT_CedFact = new javax.swing.JTextField();
        jPanel_Ficha2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jT_Adulto = new javax.swing.JTextField();
        jT_Menor = new javax.swing.JTextField();
        jT_TercerEdad = new javax.swing.JTextField();
        jL_PA = new javax.swing.JLabel();
        jL_PM = new javax.swing.JLabel();
        jL_PTE = new javax.swing.JLabel();
        jL_PASUB = new javax.swing.JLabel();
        jL_PMSUB = new javax.swing.JLabel();
        jL_PTESUB = new javax.swing.JLabel();
        BT_Calcular = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jL_Desc = new javax.swing.JLabel();
        jL_Total = new javax.swing.JLabel();
        BT_Back2 = new javax.swing.JButton();
        BT_Impress = new javax.swing.JButton();
        BT_Cerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FACTURA");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel_Ficha.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_Ficha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ficha", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel_Ficha.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TITULO: ");

        jL_TituloFact.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SALA:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("HORA:");

        jL_SalaFact.setForeground(new java.awt.Color(255, 255, 255));

        jL_SillasFact.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SILLAS: ");

        jL_HoraFact.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Sillas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("CANT:");

        cantSillas.setForeground(new java.awt.Color(255, 255, 255));
        cantSillas.setText("0");

        javax.swing.GroupLayout jPanel_FichaLayout = new javax.swing.GroupLayout(jPanel_Ficha);
        jPanel_Ficha.setLayout(jPanel_FichaLayout);
        jPanel_FichaLayout.setHorizontalGroup(
            jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FichaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_FichaLayout.createSequentialGroup()
                        .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_FichaLayout.createSequentialGroup()
                                .addComponent(jL_TituloFact, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addComponent(jL_SalaFact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_HoraFact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_FichaLayout.createSequentialGroup()
                        .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_FichaLayout.createSequentialGroup()
                                .addComponent(jL_SillasFact, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(jPanel_FichaLayout.createSequentialGroup()
                                .addComponent(cantSillas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel_FichaLayout.setVerticalGroup(
            jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FichaLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jL_TituloFact, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jL_SalaFact, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_FichaLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel8))
                    .addComponent(jL_HoraFact, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(jL_SillasFact, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel_FichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(cantSillas, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        jPanel_Ficha1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_Ficha1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel_Ficha1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMBRE:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CEDULA:");

        javax.swing.GroupLayout jPanel_Ficha1Layout = new javax.swing.GroupLayout(jPanel_Ficha1);
        jPanel_Ficha1.setLayout(jPanel_Ficha1Layout);
        jPanel_Ficha1Layout.setHorizontalGroup(
            jPanel_Ficha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Ficha1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_Ficha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Ficha1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel_Ficha1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(7, 7, 7)))
                .addGroup(jPanel_Ficha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jT_NombreFact, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jT_CedFact))
                .addGap(50, 50, 50))
        );
        jPanel_Ficha1Layout.setVerticalGroup(
            jPanel_Ficha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Ficha1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_Ficha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jT_NombreFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel_Ficha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jT_CedFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        jPanel_Ficha2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_Ficha2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel_Ficha2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TIPO ");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CANTIDAD");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PRECIO C/U");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SUB ");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ADULTO:");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("MENOR:");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TERCERA EDAD:");

        jT_TercerEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_TercerEdadActionPerformed(evt);
            }
        });

        jL_PA.setForeground(new java.awt.Color(255, 255, 255));

        jL_PM.setForeground(new java.awt.Color(255, 255, 255));

        jL_PTE.setForeground(new java.awt.Color(255, 255, 255));

        jL_PASUB.setForeground(new java.awt.Color(255, 255, 255));

        jL_PMSUB.setForeground(new java.awt.Color(255, 255, 255));

        jL_PTESUB.setForeground(new java.awt.Color(255, 255, 255));

        BT_Calcular.setText("Calcular");
        BT_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CalcularActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DESCUENTO:");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("TOTAL:");

        jL_Desc.setForeground(new java.awt.Color(255, 255, 255));

        jL_Total.setForeground(new java.awt.Color(255, 255, 255));

        BT_Back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonBack1.png"))); // NOI18N
        BT_Back2.setBorder(null);
        BT_Back2.setBorderPainted(false);
        BT_Back2.setContentAreaFilled(false);
        BT_Back2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BT_Back2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonBack2.png"))); // NOI18N
        BT_Back2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BT_Back2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BT_Back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_Back2ActionPerformed(evt);
            }
        });

        BT_Impress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonVer1.png"))); // NOI18N
        BT_Impress.setBorder(null);
        BT_Impress.setBorderPainted(false);
        BT_Impress.setContentAreaFilled(false);
        BT_Impress.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonVer2.png"))); // NOI18N
        BT_Impress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ImpressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Ficha2Layout = new javax.swing.GroupLayout(jPanel_Ficha2);
        jPanel_Ficha2.setLayout(jPanel_Ficha2Layout);
        jPanel_Ficha2Layout.setHorizontalGroup(
            jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Ficha2Layout.createSequentialGroup()
                .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Ficha2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Ficha2Layout.createSequentialGroup()
                                .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jL_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_Ficha2Layout.createSequentialGroup()
                                .addComponent(BT_Calcular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(BT_Impress)
                                .addGap(43, 43, 43)
                                .addComponent(BT_Back2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel_Ficha2Layout.createSequentialGroup()
                        .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Ficha2Layout.createSequentialGroup()
                                .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jT_Adulto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jT_Menor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jT_TercerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Ficha2Layout.createSequentialGroup()
                                .addComponent(jL_PM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jL_PMSUB, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_Ficha2Layout.createSequentialGroup()
                                .addComponent(jL_PTE, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jL_PTESUB, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_Ficha2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addGroup(jPanel_Ficha2Layout.createSequentialGroup()
                                .addComponent(jL_PA, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jL_PASUB, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel_Ficha2Layout.setVerticalGroup(
            jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Ficha2Layout.createSequentialGroup()
                .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Ficha2Layout.createSequentialGroup()
                        .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jT_Adulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jL_PA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jL_PASUB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_PM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel_Ficha2Layout.createSequentialGroup()
                                .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jT_Menor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel_Ficha2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jL_PMSUB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Ficha2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jL_PTESUB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jL_PTE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_Ficha2Layout.createSequentialGroup()
                        .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_TercerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(20, 20, 20)
                .addGroup(jPanel_Ficha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BT_Back2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_Calcular)
                    .addComponent(BT_Impress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_Ficha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_Ficha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_Ficha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel_Ficha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_Ficha1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_Ficha2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 130, 780, 340);

        BT_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        BT_Cerrar.setBorder(null);
        BT_Cerrar.setBorderPainted(false);
        BT_Cerrar.setContentAreaFilled(false);
        BT_Cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BT_Cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar2.png"))); // NOI18N
        BT_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(BT_Cerrar);
        BT_Cerrar.setBounds(740, 0, 53, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 610);

        setSize(new java.awt.Dimension(796, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        sillas miSillas = new sillas();
        miSillas.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jT_TercerEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_TercerEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_TercerEdadActionPerformed

    private void BT_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CalcularActionPerformed
        // TODO add your handling code here:
        int cant = Integer.parseInt(this.cantSillas.getText());
      

        int PM , PA, PTE , cA = 0, cM = 0, cTE = 0, subPM = 0, subPA = 0, subPTE = 0, cantB;
        double total, descuento, totalD;
        String adulto = this.jT_Adulto.getText(), menor = this.jT_Menor.getText(), tercera = this.jT_TercerEdad.getText();

        if (adulto.equals("") == true|| adulto.equals("0") == true ) {
            this.jT_Adulto.setText("0");
            PA=0;
        }else {PA=9000;}

        if (menor.equals("") == true||menor.equals("0") == true) {
            this.jT_Menor.setText("0");
            PM=0;
            
        }else {PM=7000;} 
        if (tercera.equals("") == true|| tercera.equals("0") == true) {
            this.jT_TercerEdad.setText("0");
            PTE=0;
        } else 
        {
        
        PTE=5000;
        }

        cA = Integer.parseInt(this.jT_Adulto.getText());
        cM = Integer.parseInt(this.jT_Menor.getText());
        cTE = Integer.parseInt(this.jT_TercerEdad.getText());

        cantB = cA + cM + cTE;
        if (cantB == cant) {
            subPA = PA * cA;
            subPM = PM * cM;
            subPTE = PTE * cTE;

            if (cantB > 5) {
                total = subPA + subPTE + subPM;
                descuento = total * 0.3;
                totalD = total - descuento;
                this.jL_Total.setText(String.valueOf(totalD));

            } else {
                total = subPA + subPTE + subPM;
                descuento = 0;
                this.jL_Total.setText(String.valueOf(total));
            }

            this.jL_Desc.setText(String.valueOf(descuento));

            this.jL_PM.setText(String.valueOf(PM));
            this.jL_PA.setText(String.valueOf(PA));

            this.jL_PTE.setText(String.valueOf(PTE));

            this.jL_PASUB.setText(String.valueOf(subPA));
            this.jL_PMSUB.setText(String.valueOf(subPM));
            this.jL_PTESUB.setText(String.valueOf(subPTE));
        } else {
            JOptionPane.showMessageDialog(null, "Número de boletas erróneo", "Inválido", JOptionPane.ERROR_MESSAGE);

        }
        
       
        

    }//GEN-LAST:event_BT_CalcularActionPerformed

    private void BT_Back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_Back2ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "\n¿Desea regresar?",
                "Confirmar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            this.dispose();
            cartelera miCar = new cartelera();
            miCar.setVisible(true);
        }
    }//GEN-LAST:event_BT_Back2ActionPerformed

    private void BT_ImpressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ImpressActionPerformed
        // TODO add your handling code here:

        impress miI = new impress();
        // Nombre, cedula, título, sala, hora, sillas, cantidad, adulto , menor, tercera edad, (cantidad, precio u, sub total)
        impress.jL_NomImpress.setText(jT_NombreFact.getText());
        impress.jL_CedulaImpress.setText(jT_CedFact.getText());
        impress.jL_TitImpress.setText(jL_TituloFact.getText());
        impress.jL_SalaImpress.setText(jL_SalaFact.getText());
        impress.jL_HoraImpress.setText(jL_HoraFact.getText());
        impress.jL_SillasImpress.setText(jL_SillasFact.getText());
        impress.jL_CantImpress.setText(cantSillas.getText());
        impress.jL_AImpress.setText(jT_Adulto.getText());
        impress.jL_MImpress.setText(jT_Menor.getText());
        impress.jL_TEImpress.setText(jT_TercerEdad.getText());
        impress.jL_AImpressPrecioCU.setText(jL_PA.getText());
        impress.jL_MImpressPrecioCU.setText(jL_PM.getText());
        impress.jL_TEImpressPrecioCU.setText(jL_PTE.getText());
        impress.jL_AImpressPrecioSUB.setText(jL_PASUB.getText());
        impress.jL_MImpressPrecioSUB.setText(jL_PMSUB.getText());
        impress.jL_TEImpressPrecioSUB.setText(jL_PTESUB.getText());
        impress.jL_DescImpress.setText(jL_Desc.getText());
        impress.jL_TotalImpress.setText(jL_Total.getText());

        
        miI.setVisible(true);

           try {
            PrinterJob impr = PrinterJob.getPrinterJob();
            impr.setPrintable((Printable) this);

            boolean validar = impr.printDialog();

            if (validar) {
                impr.print();
            }

        } catch (java.awt.print.PrinterException error) {

            JOptionPane.showMessageDialog(null, "ERROR DE IMPRESIÓN", "Error", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_BT_ImpressActionPerformed

    private void BT_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CerrarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "\n¿Desea salir del programa?",
            "Confirmar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
        System.exit(0);}

    }//GEN-LAST:event_BT_CerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Back2;
    private javax.swing.JButton BT_Calcular;
    private javax.swing.JButton BT_Cerrar;
    private javax.swing.JButton BT_Impress;
    public static javax.swing.JLabel cantSillas;
    private javax.swing.JButton jButton1;
    public static javax.swing.JLabel jL_Desc;
    public static javax.swing.JLabel jL_HoraFact;
    public static javax.swing.JLabel jL_PA;
    public static javax.swing.JLabel jL_PASUB;
    public static javax.swing.JLabel jL_PM;
    public static javax.swing.JLabel jL_PMSUB;
    public static javax.swing.JLabel jL_PTE;
    public static javax.swing.JLabel jL_PTESUB;
    public static javax.swing.JLabel jL_SalaFact;
    public static javax.swing.JLabel jL_SillasFact;
    public static javax.swing.JLabel jL_TituloFact;
    public static javax.swing.JLabel jL_Total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Ficha;
    private javax.swing.JPanel jPanel_Ficha1;
    private javax.swing.JPanel jPanel_Ficha2;
    public static javax.swing.JTextField jT_Adulto;
    public static javax.swing.JTextField jT_CedFact;
    public static javax.swing.JTextField jT_Menor;
    public static javax.swing.JTextField jT_NombreFact;
    public static javax.swing.JTextField jT_TercerEdad;
    // End of variables declaration//GEN-END:variables

    
    public int print(Graphics graf, PageFormat pagfor, int index) throws java.awt.print.PrinterException {
        
        if (index>0) {
            return NO_SUCH_PAGE;
        }
        Graphics2D panelImpr= (Graphics2D) graf;
        panelImpr.translate(pagfor.getImageableX()+0, pagfor.getImageableY()+100);
        panelImpr.scale(0.7, 0.7);
        impress.jPanel1.paintAll(graf);
        return PAGE_EXISTS;
    }

}
