/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author Alumno
 */
public class sillas extends javax.swing.JFrame {

    /**
     * Creates new form cartelera
     */
    public sillas() {
        initComponents();
      
       setIconImage(new ImageIcon(getClass().getResource("/imagenes/imgCam.png")).getImage());

          
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        A1 = new javax.swing.JCheckBox();
        A2 = new javax.swing.JCheckBox();
        A3 = new javax.swing.JCheckBox();
        A4 = new javax.swing.JCheckBox();
        A5 = new javax.swing.JCheckBox();
        A6 = new javax.swing.JCheckBox();
        A7 = new javax.swing.JCheckBox();
        B1 = new javax.swing.JCheckBox();
        B2 = new javax.swing.JCheckBox();
        B3 = new javax.swing.JCheckBox();
        B4 = new javax.swing.JCheckBox();
        B5 = new javax.swing.JCheckBox();
        B6 = new javax.swing.JCheckBox();
        B7 = new javax.swing.JCheckBox();
        C1 = new javax.swing.JCheckBox();
        C2 = new javax.swing.JCheckBox();
        C3 = new javax.swing.JCheckBox();
        C4 = new javax.swing.JCheckBox();
        C5 = new javax.swing.JCheckBox();
        C6 = new javax.swing.JCheckBox();
        C7 = new javax.swing.JCheckBox();
        D1 = new javax.swing.JCheckBox();
        D2 = new javax.swing.JCheckBox();
        D3 = new javax.swing.JCheckBox();
        D4 = new javax.swing.JCheckBox();
        D5 = new javax.swing.JCheckBox();
        D6 = new javax.swing.JCheckBox();
        D7 = new javax.swing.JCheckBox();
        BT_Aceptar = new javax.swing.JButton();
        BT_Back2 = new javax.swing.JButton();
        BT_Cerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Pantalla");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        A1.setBorder(null);
        A1.setContentAreaFilled(false);
        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        A1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });

        A2.setBorder(null);
        A2.setContentAreaFilled(false);
        A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        A2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });

        A3.setBorder(null);
        A3.setContentAreaFilled(false);
        A3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        A3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });

        A4.setBorder(null);
        A4.setContentAreaFilled(false);
        A4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        A4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });

        A5.setBorder(null);
        A5.setContentAreaFilled(false);
        A5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        A5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });

        A6.setBorder(null);
        A6.setContentAreaFilled(false);
        A6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        A6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6ActionPerformed(evt);
            }
        });

        A7.setBorder(null);
        A7.setContentAreaFilled(false);
        A7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        A7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        A7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A7ActionPerformed(evt);
            }
        });

        B1.setBorder(null);
        B1.setContentAreaFilled(false);
        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        B1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setBorder(null);
        B2.setContentAreaFilled(false);
        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        B2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setBorder(null);
        B3.setContentAreaFilled(false);
        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        B3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B4.setBorder(null);
        B4.setContentAreaFilled(false);
        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        B4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setBorder(null);
        B5.setContentAreaFilled(false);
        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        B5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setBorder(null);
        B6.setContentAreaFilled(false);
        B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        B6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        B7.setBorder(null);
        B7.setContentAreaFilled(false);
        B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        B7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        C1.setBorder(null);
        C1.setContentAreaFilled(false);
        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        C1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });

        C2.setBorder(null);
        C2.setContentAreaFilled(false);
        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        C2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });

        C3.setBorder(null);
        C3.setContentAreaFilled(false);
        C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        C3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });

        C4.setBorder(null);
        C4.setContentAreaFilled(false);
        C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        C4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });

        C5.setBorder(null);
        C5.setContentAreaFilled(false);
        C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        C5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5ActionPerformed(evt);
            }
        });

        C6.setBorder(null);
        C6.setContentAreaFilled(false);
        C6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        C6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C6ActionPerformed(evt);
            }
        });

        C7.setBorder(null);
        C7.setContentAreaFilled(false);
        C7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        C7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C7ActionPerformed(evt);
            }
        });

        D1.setBorder(null);
        D1.setContentAreaFilled(false);
        D1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        D1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ActionPerformed(evt);
            }
        });

        D2.setBorder(null);
        D2.setContentAreaFilled(false);
        D2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        D2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2ActionPerformed(evt);
            }
        });

        D3.setBorder(null);
        D3.setContentAreaFilled(false);
        D3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        D3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3ActionPerformed(evt);
            }
        });

        D4.setBorder(null);
        D4.setContentAreaFilled(false);
        D4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        D4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        D4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D4ActionPerformed(evt);
            }
        });

        D5.setBorder(null);
        D5.setContentAreaFilled(false);
        D5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        D5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        D5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D5ActionPerformed(evt);
            }
        });

        D6.setBorder(null);
        D6.setContentAreaFilled(false);
        D6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        D6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        D6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D6ActionPerformed(evt);
            }
        });

        D7.setBorder(null);
        D7.setContentAreaFilled(false);
        D7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla1.png"))); // NOI18N
        D7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/silla2.png"))); // NOI18N
        D7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D7ActionPerformed(evt);
            }
        });

        BT_Aceptar.setBackground(new java.awt.Color(255, 255, 255));
        BT_Aceptar.setText("Aceptar");
        BT_Aceptar.setBorder(null);
        BT_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_AceptarActionPerformed(evt);
            }
        });

        BT_Back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonBack1.png"))); // NOI18N
        BT_Back2.setBorder(null);
        BT_Back2.setBorderPainted(false);
        BT_Back2.setContentAreaFilled(false);
        BT_Back2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BT_Back2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonBack2.png"))); // NOI18N
        BT_Back2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BT_Back2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BT_Back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_Back2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(D1)
                        .addGap(18, 18, 18)
                        .addComponent(D2)
                        .addGap(18, 18, 18)
                        .addComponent(D3)
                        .addGap(18, 18, 18)
                        .addComponent(D4)
                        .addGap(18, 18, 18)
                        .addComponent(D5)
                        .addGap(18, 18, 18)
                        .addComponent(D6)
                        .addGap(18, 18, 18)
                        .addComponent(D7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(C1)
                        .addGap(18, 18, 18)
                        .addComponent(C2)
                        .addGap(18, 18, 18)
                        .addComponent(C3)
                        .addGap(18, 18, 18)
                        .addComponent(C4)
                        .addGap(18, 18, 18)
                        .addComponent(C5)
                        .addGap(18, 18, 18)
                        .addComponent(C6)
                        .addGap(18, 18, 18)
                        .addComponent(C7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(B1)
                        .addGap(18, 18, 18)
                        .addComponent(B2)
                        .addGap(18, 18, 18)
                        .addComponent(B3)
                        .addGap(18, 18, 18)
                        .addComponent(B4)
                        .addGap(18, 18, 18)
                        .addComponent(B5)
                        .addGap(18, 18, 18)
                        .addComponent(B6)
                        .addGap(18, 18, 18)
                        .addComponent(B7))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(A1)
                            .addGap(18, 18, 18)
                            .addComponent(A2)
                            .addGap(18, 18, 18)
                            .addComponent(A3)
                            .addGap(18, 18, 18)
                            .addComponent(A4)
                            .addGap(18, 18, 18)
                            .addComponent(A5)
                            .addGap(18, 18, 18)
                            .addComponent(A6)
                            .addGap(18, 18, 18)
                            .addComponent(A7))))
                .addGap(190, 190, 190))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(BT_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(BT_Back2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(BT_Back2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BT_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A2)
                            .addComponent(A1)
                            .addComponent(A3)
                            .addComponent(A4)
                            .addComponent(A5)
                            .addComponent(A6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B5)
                            .addComponent(B6)
                            .addComponent(B4)
                            .addComponent(B3)
                            .addComponent(B2)
                            .addComponent(B1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(A7)
                        .addGap(18, 18, 18)
                        .addComponent(B7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(C2)
                            .addComponent(C1)
                            .addComponent(C3)
                            .addComponent(C4)
                            .addComponent(C5)
                            .addComponent(C6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D5)
                            .addComponent(D6)
                            .addComponent(D4)
                            .addComponent(D3)
                            .addComponent(D2)
                            .addComponent(D1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(C7)
                        .addGap(18, 18, 18)
                        .addComponent(D7)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 140, 720, 350);

        BT_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        BT_Cerrar.setBorder(null);
        BT_Cerrar.setBorderPainted(false);
        BT_Cerrar.setContentAreaFilled(false);
        BT_Cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BT_Cerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar2.png"))); // NOI18N
        BT_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(BT_Cerrar);
        BT_Cerrar.setBounds(740, 0, 53, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 610);

        setSize(new java.awt.Dimension(796, 611));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A4ActionPerformed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A5ActionPerformed

    private void A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A6ActionPerformed

    private void A7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A7ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B7ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C1ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C2ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C3ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C4ActionPerformed

    private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C5ActionPerformed

    private void C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C6ActionPerformed

    private void C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C7ActionPerformed

    private void D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D1ActionPerformed

    private void D2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D2ActionPerformed

    private void D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D3ActionPerformed

    private void D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D4ActionPerformed

    private void D5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D5ActionPerformed

    private void D6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D6ActionPerformed

    private void D7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D7ActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
       
    
    }//GEN-LAST:event_A1ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_A2ActionPerformed

    private void BT_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_AceptarActionPerformed
        // TODO add your handling code here:
        String sillas="";
        int cant=0;
        
        if (A1.isSelected()==true){
            sillas=sillas+" A1;";
            cant=cant+1;
        }
        if (A2.isSelected()==true){
            sillas=sillas+" A2;";
                        cant=cant+1;

        }
        if (A3.isSelected()==true){
            sillas=sillas+" A3;";
                        cant=cant+1;

        }
        if (A4.isSelected()==true){
            sillas=sillas+" A4;";
                        cant=cant+1;

        }
        if (A5.isSelected()==true){
            sillas=sillas+" A5;";
                        cant=cant+1;

        }
        if (A6.isSelected()==true){
            sillas=sillas+" A6;";
                        cant=cant+1;

        }
        if (A7.isSelected()==true){
            sillas=sillas+" A7;";
                        cant=cant+1;

        }
        if (B1.isSelected()==true){
            sillas=sillas+" B1;";
                        cant=cant+1;

        }
         if (B2.isSelected()==true){
            sillas=sillas+" B2;";
                        cant=cant+1;

        }
          if (B3.isSelected()==true){
            sillas=sillas+" B3;";
                        cant=cant+1;

        }
           if (B4.isSelected()==true){
            sillas=sillas+" B4;";
                        cant=cant+1;

        }
            if (B5.isSelected()==true){
            sillas=sillas+" B5;";
                        cant=cant+1;

        }
             if (B6.isSelected()==true){
            sillas=sillas+" B6;";
                        cant=cant+1;

        }
              if (B7.isSelected()==true){
            sillas=sillas+" B7;";
                        cant=cant+1;

        }
                if (D1.isSelected()==true){
            sillas=sillas+" D1;";
                        cant=cant+1;

        }
         if (D2.isSelected()==true){
            sillas=sillas+" D2;";
                        cant=cant+1;

        }
          if (D3.isSelected()==true){
            sillas=sillas+" D3;";
                        cant=cant+1;

        }
           if (D4.isSelected()==true){
            sillas=sillas+" D4;";
                        cant=cant+1;

        }
            if (D5.isSelected()==true){
            sillas=sillas+" D5;";
                        cant=cant+1;

        }
             if (D6.isSelected()==true){
            sillas=sillas+" D6;";
                        cant=cant+1;

        }
              if (D7.isSelected()==true){
            sillas=sillas+" D7;";
                        cant=cant+1;

        }
                if (C1.isSelected()==true){
            sillas=sillas+" C1;";
                        cant=cant+1;

        }
         if (C2.isSelected()==true){
            sillas=sillas+" C2;";
                        cant=cant+1;

        }
          if (C3.isSelected()==true){
            sillas=sillas+" C3;";

                      cant=cant+1;
}
           if (C4.isSelected()==true){
            sillas=sillas+" C4;";
                        cant=cant+1;

        }
            if (C5.isSelected()==true){
            sillas=sillas+" C5;";
                        cant=cant+1;

        }
             if (C6.isSelected()==true){
            sillas=sillas+" C6;";
                        cant=cant+1;

        }
              if (C7.isSelected()==true){
            sillas=sillas+" C7;";
                        cant=cant+1;

        }
              
               if (JOptionPane.showConfirmDialog(rootPane, "Sus sillas son: "+ sillas + "\nCantidad: "+ cant+"\n¿Desea confirmar selección?",
                "Confirmar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
         
                 factura.cantSillas.setText(String.valueOf(cant));
                        

       
        factura.jL_SillasFact.setText(sillas);
         this.dispose();
               }
    }//GEN-LAST:event_BT_AceptarActionPerformed

    private void BT_Back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_Back2ActionPerformed
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog(rootPane, "\n¿Desea regresar?",
                "Confirmar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
        this.dispose();
         }
        
        
    }//GEN-LAST:event_BT_Back2ActionPerformed

    private void BT_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CerrarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "\n¿Desea salir del programa?",
            "Confirmar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
        System.exit(0);}

    }//GEN-LAST:event_BT_CerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sillas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox A1;
    public javax.swing.JCheckBox A2;
    private javax.swing.JCheckBox A3;
    private javax.swing.JCheckBox A4;
    private javax.swing.JCheckBox A5;
    private javax.swing.JCheckBox A6;
    private javax.swing.JCheckBox A7;
    private javax.swing.JCheckBox B1;
    private javax.swing.JCheckBox B2;
    private javax.swing.JCheckBox B3;
    private javax.swing.JCheckBox B4;
    private javax.swing.JCheckBox B5;
    private javax.swing.JCheckBox B6;
    private javax.swing.JCheckBox B7;
    public javax.swing.JButton BT_Aceptar;
    private javax.swing.JButton BT_Back2;
    private javax.swing.JButton BT_Cerrar;
    private javax.swing.JCheckBox C1;
    private javax.swing.JCheckBox C2;
    private javax.swing.JCheckBox C3;
    private javax.swing.JCheckBox C4;
    private javax.swing.JCheckBox C5;
    private javax.swing.JCheckBox C6;
    private javax.swing.JCheckBox C7;
    private javax.swing.JCheckBox D1;
    private javax.swing.JCheckBox D2;
    private javax.swing.JCheckBox D3;
    private javax.swing.JCheckBox D4;
    private javax.swing.JCheckBox D5;
    private javax.swing.JCheckBox D6;
    private javax.swing.JCheckBox D7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
